name: employee_churn_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas
      - scikit-learn
      - joblib
      - mlflow
      - xgboost
      - lightgbm
      - catboost
